### ISSUE TITLE
How to turn on the logs?

### ISSUE THREAD

**Issue by Hongbo-Miao** [authorizon/opal-fetcher-postgres#4]
I saw some code in the `provider` [file](https://github.com/authorizon/opal-fetcher-postgres/blob/406d4312426e8b4023ab1ea6ba1cdb8c4849b4f1/opal_fetcher_postgres/provider.py#L134).

```py
from opal_common.logger import logger
logger.debug('...')
```

I also tried to add some

```
print('...')
```
However, they never got printed after I `docker compose up --build`.

How can I turn on the logs? Thanks!

**Comment by orweis** [comment]
Hi @Hongbo-Miao ,
Check out the config flags  (starting with LOG_) at `opal_common/config.py`
(Also remember to prefix with `OPAL_` when defining as env-vars)

You can see that the default log level is `INFO`
```python
    #  - log level
    LOG_LEVEL = confi.str("LOG_LEVEL", "INFO")
```

and so only logs equal or higher are logged, `debug` is below and hence ignored.

**Comment by Hongbo-Miao** [comment]
Thanks @orweis , adding `OPAL_LOG_LEVEL=DEBUG` makes `logger.debug('...')` works!
I am surprised my `print('...')` not print.

**Comment by orweis** [comment]
Regarding the print - the server config is to propagate out stderr , and not stdout (you can change print of course see - https://www.systutorials.com/how-to-print-a-line-to-stderr-and-stdout-in-python/)

**Comment by Hongbo-Miao** [comment]
Oh I see, thanks for the info, @orweis !

**Comment by kivo360** [comment]
Low key, check out loguru. It adds bloat to your project, but you have easy global controls in libraries using the `configure`, `enable` and `disable` commands.
